module.exports = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
    channelsidebar: ['Channels/omnichannel', 'Channels/whatsappchannel', 'Channels/facebookchannel', 'Channels/instagramchannel', 'Channels/telegramchannel', 'Channels/gmgchannel', 'Channels/slackchannel'],
  
    // But you can create a sidebar manually
    /*
    tutorialSidebar: [
      {
        type: 'category',
        label: 'Tutorial',
        items: ['hello'],
      },
    ],
     */
  };